name: 'Deploy ASP.NET Core app to Azure Web App1'

on:
  push:
    branches:
      - "main"

env:
  DOTNET_VERSION: '3.1.404'


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      - name: Build and plan
        run: |
          echo "DEPLOYMENT_URL = Build and plan" 

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: build-and-publish
    steps:

      - name: Publish Dev environment
        run: |
          echo "DEPLOYMENT_URL=Dev" 
  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [build-and-publish, deploy-dev]
    steps:

      - name: Publish Prod environment
        run: |
          echo "DEPLOYMENT_URL= Prod" 
